### ISSUE TITLE
Is there capability to use with a proxy

### ISSUE THREAD

**Issue by cagilla** [TypicalAM/goread#14]
This project looks great!  Unfortunately it doesn't appear to work through a corporate proxy.

I attempted to set environment variable "https_proxy=user:pass@proxy.com" but this did not work.  

Anything else I should try - or is this a new feature request?

**Comment by TypicalAM** [comment]
Hi! This is more of a feature request since we do not support proxies right now. Will work on it though

**Comment by TypicalAM** [comment]
Should be working now in [v1.3.3](https://github.com/TypicalAM/goread/releases/tag/v1.3.3)! Check it out
