### ISSUE TITLE
Feature Request:  Add support to import OPML files

### ISSUE THREAD

**Issue by 8none1** [TypicalAM/goread#19]
Web apps such as Feedly allow you to export your subscriptions to an OPML file (XML).

It'd be really great if I could import that directly in to goread without having to convert it first.

**Comment by TypicalAM** [comment]
Should be working with #21, will update release soon.

**Comment by TypicalAM** [comment]
Live in [v1.5.1](https://github.com/TypicalAM/goread/releases/tag/v1.5.1])!

**Comment by 8none1** [comment]
Thank you!
