### ISSUE TITLE
Feature Request: hjkl navigation on the welcome page

### ISSUE THREAD

**Issue by tompflynn** [TypicalAM/goread#3]
this is an awesome project, I hope you keep working on this because it's better than newsboat already.

**Comment by TypicalAM** [comment]
Thank you! In the near future I will probably add configurable keybinds in general (the vim movement could be used as a preset). For now it will get a help wanted tag and maybe someone can contribute as I am very busy with uni.

**Comment by whoop-t** [comment]
@TypicalAM Could quickly add these with this [pr](https://github.com/TypicalAM/goread/pull/4)
