### ISSUE TITLE
Images Not Showing Up

### ISSUE THREAD

**Issue by ghost3jelly** [TypicalAM/goread#33]
Hello. I am trying to make images preview in my articles but for some reason I cant manage to make it work. Any help will be much appreciated.

**Comment by TypicalAM** [comment]
Do you mean that:
1) The source links for the images don't appear/aren't accessible or 
2) The images don't get displayed (like with some terminals that have image support, `kitty` for example)

If that's the second case we don't support terminal image previews for now. Implementing paging could allow the user to wrap the article it in a preview script  - something like [this](https://github.com/newsboat/newsboat/issues/480). Could you specify what do you mean?

**Comment by TypicalAM** [comment]
Closed because stale
