### ISSUE TITLE
Feeds only displaying links to page

### ISSUE THREAD

**Issue by Jack-Chronicle** [TypicalAM/goread#38]
Not sure if I have an issue on my end, but every feed shows up as normal until I try to view any of the pages

They just show the title, published date, and a link to the page

**Comment by TypicalAM** [comment]
Could you specify the version of the app and also the feed you're trying to view (if u can ofc)?

**Comment by Jack-Chronicle** [comment]
Goread v1.6.2

These two are the only feed I'm currently using
https://obsidian.md/changelog.xml
https://obsidian.md/feed.xml

**Comment by TypicalAM** [comment]
Will fix soon

**Comment by TypicalAM** [comment]
Should be working in [v1.6.3](https://github.com/TypicalAM/goread/releases/tag/v1.6.3)!
