### ISSUE TITLE
Sync with freshrss?

### ISSUE THREAD

**Issue by ilovethensa** [TypicalAM/goread#39]
Syncing with freshrss would be really handy i really like this project but having to constantly keep it in sync with my freshrss instance is quite annoying

**Comment by TypicalAM** [comment]
Will explore their API and think about it in the near future

**Comment by TypicalAM** [comment]
Adding this would require revamping into adding something like an `options.yml` file which would add another config and break existing versions (and also make the app more complicated). As for your issue, it can be solved with just a freshrss side crontab to export it and doing a `--load_opml` on the `goread` side automatically.
