### ISSUE TITLE
Most article titles are truncated in the article list

### ISSUE THREAD

**Issue by focusaurus** [TypicalAM/goread#40]
Even running my terminal full width, most articles only show about 7 words max before they are truncated. I find this really frustrating. Suggestions: either word wrap or make the column wider.

**Comment by TypicalAM** [comment]
Didn't know. Will work on it.

**Comment by TypicalAM** [comment]
Descriptions should be wrapped correctly now, as of 94b0ee0. Will do new release tmrw.

**Comment by TypicalAM** [comment]
Fixed in [v1.6.4](https://github.com/TypicalAM/goread/releases/v1.6.4)!
