### ISSUE TITLE
Conflicting keybinds for u key

### ISSUE THREAD

**Issue by jship** [TypicalAM/goread#44]
The help screen for a feed's listing has conflicting keybinds for the `u` key:

![image](https://github.com/TypicalAM/goread/assets/1744045/e27deffa-4477-434c-b114-a6381bd38d4f)

Pressing `u` will mark a post as unread, and the "1/2 page up" action isn't triggerable as far as I can tell. This issue would be resolved via #20.

`goread version v1.6.4`

**Comment by TypicalAM** [comment]
Hi! I'm thinking of scraping the tertiary keybind column alltogether because the `key.Binding` doesn't play well with conflicts. Will get back on this soon.

**Comment by TypicalAM** [comment]
Solved in [v1.6.5](https://github.com/TypicalAM/goread/releases/tag/v1.6.5)!
