### ISSUE TITLE
Make tests not rely on network access

### ISSUE THREAD

**Issue by kanielrkirby** [TypicalAM/goread#45]
For starters, just want to commend you on this project! Love bubbletea, and TUIs in general, and this has been helping me quite a bit in getting into this RSS space!

In trying to package this for NixOS, the main issue I ran into is that it doesn't properly package this, because Nix builds run sandboxed from the network (for reproducibility reasons). It might benefit the project to have a build process that doesn't require network access, if at all possible.

If not, feel free to close the issue. I can simple pass the following into it to bypass the test suite so we can get a proper build, albeit a bit hacky.

```nix
{
  ...
  doCheck = false;
  ...
}
```

Also happy to have a hand at implementing this myself, if it's not a good use of your time!

**Comment by TypicalAM** [comment]
Thanks! I also dabble in NixOS [from time to time](https://github.com/TypicalAM/nixos-config).  Added an option to perform offline tests in #46. Use the `TEST_OFFLINE_ONLY` env var (set to a truthy value).
