### ISSUE TITLE
Usability UX issues

### ISSUE THREAD

**Issue by kqvanity** [TypicalAM/goread#47]
First off thanks for the effort you're putting into it. However, I find a couple of usability downsides
- Categories are nice, but having to click on each category to check out for new feeds is quite cumbersome, especially when you're subscribed to many feeds per category. Display category feeds all at once would be a nicer 'option' to have.
- Searching feeds in the same way as articles of a certain, would be a nice touch. Again, it's only annoying with sizeable feed lists per category when you have to scroll down manually
- Lengthy article's headline can only be viewed by 'opening' it, which first off marks it as 'read' and secondly gets cumbersome having to hit 'Enter' on each article to view its full headline. I think the fact you've already obtained the article metadata off the internet, you can just preview it as the user cycles through the articles. 
- The help popup doesn't close once opened unless I close the editor altogether.

Thanks!

**Comment by TypicalAM** [comment]
Hi, thank you for the feedback! 

already addressed the feed viewing issue in #d3a65b7 and you can now close the help bubble with any key (as of `v1.6.5`). The first two things are more difficult from the design perspective, maybe just do fuzzy search on all feed names?

**Comment by xquilt** [comment]
> maybe just do fuzzy search on all feed names?

Can you elaborate more? but for now, I don't think that's possible. An optional pane would be generally an optional solution. Simple iteration through all feeds of a certain category, then list them out chronologically based on timestamp.

> already addressed the feed viewing issue 

I'm not sure if I'm missing on something, but the previewing behavior remains the same. I think cycling through tabs, then opening links through `shift-o` is more TUI-like.

>  close the help bubble with any key 

It did resolve the issue, but still doesn't feel natural with regards with conventional TUI navigation (which usually stems from vim motion). For instance, toggle help menu would make sense through single `Shift-H`, and navigating right-left between an article/its metadata through `h-l`, etc.

**Comment by xquilt** [comment]
> Maybe just do a fuzzy search on all feed names?

Can you elaborate more? I think an optional previewing pane could be a viable solution e.g., Simple iteration through all feeds of a certain category, then list them out chronologically based on timestamp.

> already addressed the feed viewing issue 

I'm not sure if I'm missing on something, but the previewing behavior remains the same. I think cycling through tabs and then opening links through `shift-o` is more TUI-like.

> Close the help bubble with any key 

It did resolve the issue but still doesn't feel natural with regards to conventional TUI navigation (which usually stems from Vim motion). For instance, one could toggle the help menu would make sense through a single `Shift-H`, and navigating right-left between an article/its metadata through `h-l`, etc.

**Comment by TypicalAM** [comment]
> Can you elaborate more? I think an optional previewing pane could be a viable solution e.g., Simple iteration through all feeds of a certain category, then list them out chronologically based on timestamp.

If sorting the categories by the newest items in a child feed, this creates the problem of needing to fetch the articles before actually entering a category, which sucks from a time-spent-fetching-articles standpoint. We could just do an second side-pane to preview the cats 

> I'm not sure if I'm missing on something, but the previewing behavior remains the same. I think cycling through tabs and then opening links through shift-o is more TUI-like. 
> It did resolve the issue but still doesn't feel natural with regards to conventional TUI navigation (which usually stems from Vim motion). For instance, one could toggle the help menu would make sense through a single Shift-H, and navigating right-left between an article/its metadata through h-l, etc.

I designed the app to feel more like a small browser with more of a `firefox` inspired set of shortcuts (cutting the `ctrl` from them, ex `ctrl+w` or just `c` closes the tab, `tab` shifts through the tabs and such), because inventing my own from scratch would result in [this](https://xkcd.com/927/). I really like vim (actually used it to build this), but thought that introducing a few simple `firefox`-esque shortcuts would reduce needing to map non-obvious actions to vim shortcuts, maybe actually #6 can fix this, but enabling vim-like keybinds should be an option, not really a default in my vision.
