### ISSUE TITLE
how to open html?

### ISSUE THREAD

**Issue by anthonyanikos** [TypicalAM/goread#49]
Hello!
Thank u a lot for souch miracle reader!
Its look like so oldy, but modern same time ;)
Great work, for sure.

Can u say, how can i open the link inside the news?

with respect, Anthony

**Comment by TypicalAM** [comment]
Hi! After selecting an article, switch to the right pane using `right` and press `g` to start cycling through the links in the article, then press `enter` to open the article:

![image](https://github.com/TypicalAM/goread/assets/50233321/0c4671be-4205-4f51-a445-2ac59a41da54)

after that the article should automatically open in a designated browser. Hope this helps!

**Comment by anthonyanikos** [comment]
Thanks a lot!!!
