### ISSUE TITLE
macos: url.yml not being updated where it matters

### ISSUE THREAD

**Issue by sushantvema** [TypicalAM/goread#51]
updating .config/goread/urls.yml doesn't update ~/Library/Application Support/goread/urls.yml. 

Unless I manually update the urls.yml in Application Support, goread won't update my configuration.

Installed via homebrew.

**Comment by TypicalAM** [comment]
Hi! Actually, it seems that `os.UserConfigDir`, which I use for determining the config directory, expands to [`~/Library/Application Support`](https://pkg.go.dev/os#UserConfigDir) so this is intended! I will update the README with the specififc location.
